### ISSUE TITLE
LED Descriptions

### ISSUE THREAD

**Issue by jaylagorio** [EnhancedRadioDevices/915MHzEdisonExplorer#11]
Is there documentation describing what each of the LEDs indicate? Are any of them controllable programmatically?

**Comment by scottleibrand** [comment]
I believe the two LEDs next to each other are controllable by the subg_rfspy firmware.  Not sure whether the power or charging LEDs are controllable in software.

**Comment by mogar** [comment]
The two LEDs are controlled by whatever firmware is on the CC1110. As @scottleibrand mentioned, the default is subg_rfspy. You can find that software here: https://github.com/EnhancedRadioDevices/subg_rfspy

Note that you can override the default LED operation by sending a command from the Edison to turn the LEDs on or off. The readme at the subg_rfspy repo explains the command for controlling LEDs from the Edison.

By default, the LEDs blink to indicate that the board is reset, but that's it. They were used for debugging purposes, and if you look through the code you'll see where commands to turn the LEDs on or off have been commented out. We turned them all off except in a reset to save power.

**Comment by jaylagorio** [comment]
This is great, thank you!
