### ISSUE TITLE
Explorer board stop to communicate

### ISSUE THREAD

**Issue by Diadon81** [EnhancedRadioDevices/915MHzEdisonExplorer#19]
I have Intel Edison and Explorer board.

Now my explorer board stop to communicate with my medtronic minimed 722. During the booting process I see the following error messages (please check an attachement). Could some one help me to understand what is happen with this board.

PS. I am using explorer board to communicate with my Medtronic Minimed 722 pump.

▒X▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒Y▒▒jҐKERNEL VERSION: b0182929
WR: 20104000

SCU IPC: 0x800000d0 0xfffce92c

PSH miaHOB version: TNG.B0.VVBD.0000000c

microkernel built 10:14:01 Jan 13 2015

******* PSH loader *******
PCM page cache size = 192 KB
Cache Constraint = 0 Pages
Arming IPC driver ..
Adding page store pool ..
PagestoreAddr(IMR Start Address) = 0x04899000
pageStoreSize(IMR Size) = 0x00080000

*** Ready to receive application ***

U-Boot 2014.04 (Feb 09 2015 - 15:40:31)

   Watchdog enabled
DRAM: 980.6 MiB
MMC: tangier_sdhci: 0
In: serial
Out: serial
Err: serial
Hit any key to stop autoboot: 0
Target:blank
Partitioning already done...
Flashing already done...
GADGET DRIVER: usb_dnl_dfu
reading vmlinuz
5143872 bytes read in 128 ms (38.3 MiB/s)
Valid Boot Flag
Setup Size = 0x00003c00
Magic signature found
Using boot protocol version 2.0c
Linux kernel version 3.10.98-poky-edison (robin@robin-i7) #5 SMP PREEMPT Tue Apr 4 22:42:44 EDT 2017
Building boot_params at 0x00090000
Loading bzImage at address 00100000 (5128512 bytes)
Magic signature found
Kernel command line: "rootwait root=PARTUUID=012b3303-34ac-284d-99b4-34e03a2335f 4 rootfstype=ext4 console=ttyMFD2 earlyprintk=ttyMFD2,keep loglevel=4 g_multi.et hernet_config=rndis systemd.unit=multi-user.target hardware_id=00 g_multi.iSeria lNumber=b9d4eb860e4fe14df9e01d7b0f996106 g_multi.dev_addr=02:00:86:99:61:06"

Starting kernel ...

[ 0.000000] Zone ranges:
[ 0.000000] DMA [mem 0x00001000-0x00ffffff]
[ 0.000000] Normal [mem 0x01000000-0x377fdfff]
[ 0.000000] HighMem [mem 0x377fe000-0x3f4fffff]
[ 0.000000] Movable zone start for each node
[ 0.000000] Early memory node ranges
[ 0.000000] node 0: [mem 0x00001000-0x00097fff]
[ 0.000000] node 0: [mem 0x00100000-0x03ffffff]
[ 0.000000] node 0: [mem 0x06000000-0x3f4fffff]
[ 0.000000] Built 1 zonelists in Zone order, mobility grouping on. Total pag es: 249255
[ 0.213781] PCI: Probing PCI hardware
[ 0.656404] bounce pool size: 64 pages
[ 3.744522] Device: i2c-designware-pci
[ 3.744522] controller timed out
[ 3.744608] Modules linked in:
[ 3.744662] CPU: 0 PID: 1 Comm: swapper/0 Not tainted 3.10.98-poky-edison #5
[ 3.744729] Hardware name: Intel Corporation Merrifield/BODEGA BAY, BIOS 466 2014.06.23:19.20.05
[ 3.744807] f6889ab0 f6889ab0 f6889a78 c18b64f8 f6889aa0 c123e9ee c1b13ec0 f 6889acc
[ 3.744933] 000004d7 c1626520 c1626520 f5848c00 f6889b70 f5848c24 f6889ab8 c 123ea43
[ 3.745055] 00000009 f6889ab0 c1b13ec0 f6889acc f6889aec c1626520 c1b13ee4 0 00004d7
[ 3.745177] Call Trace:
[ 3.745229] [] dump_stack+0x16/0x18
[ 3.745294] [] warn_slowpath_common+0x5e/0x80
[ 3.745361] [] ? i2c_dw_xfer+0x1e0/0x5c0
[ 3.745422] [] ? i2c_dw_xfer+0x1e0/0x5c0
[ 3.745487] [] warn_slowpath_fmt+0x33/0x40
[ 3.745550] [] i2c_dw_xfer+0x1e0/0x5c0
[ 3.745617] [] _i2ctransfer+0x57/0x70
[ 3.745678] [] i2c_transfer+0x4d/0xc0
[ 3.745739] [] i2c_smbus_xfer+0x21a/0x600
[ 3.745815] [] ? idr_get_empty_slot+0x13f/0x370
[ 3.745883] [] i2c_smbus_read_word_data+0x3b/0x50
[ 3.745952] [] ? sub_preempt_count+0x3d/0x50
[ 3.746019] [] ? rawspin_unlock_irqrestore+0x26/0x50
[ 3.746089] [] ? devres_add+0x38/0x40
[ 3.746153] [] pca953x_read_regs.isra.5+0x2e/0xd0
[ 3.746223] [] ? _mutexinit+0x44/0x50
[ 3.746286] [] pca953x_probe+0x1b2/0x4b0
[ 3.746350] [] ? sysfs_do_create_link_sd+0xac/0x1d0
[ 3.746417] [] ? notifier_call_chain+0x41/0x60
[ 3.746486] [] ? _blockingnotifier_call_chain+0x44/0x60
[ 3.746562] [] i2c_device_probe+0x99/0x110
[ 3.746624] [] ? sysfs_create_link+0x22/0x40
[ 3.746690] [] ? pca953x_irq_handler+0x270/0x270
[ 3.746760] [] driver_probe_device+0x83/0x3a0
[ 3.746824] [] ? sub_preempt_count+0x3d/0x50
[ 3.746889] [] ? driver_probe_device+0x3a0/0x3a0
[ 3.746957] [] ? driver_probe_device+0x3a0/0x3a0
[ 3.747024] [] _deviceattach+0x31/0x40
[ 3.747086] [] bus_for_each_drv+0x47/0x80
[ 3.747150] [] device_attach+0x73/0x90
[ 3.747211] [] ? driver_probe_device+0x3a0/0x3a0
[ 3.747278] [] bus_probe_device+0x6f/0x90
[ 3.747341] [] device_add+0x5a5/0x680
[ 3.747402] [] ? complete_all+0x48/0x50
[ 3.747464] [] ? pm_runtime_init+0xcd/0xe0
[ 3.747528] [] device_register+0x17/0x20
[ 3.747589] [] i2c_new_device+0x128/0x1c0
[ 3.747654] [] ? class_compat_create_link+0x48/0x80
[ 3.747723] [] i2c_register_adapter+0x1d7/0x310
[ 3.747791] [] i2c_add_numbered_adapter+0x59/0x90
[ 3.747859] [] i2c_dw_setup+0x282/0x330
[ 3.747923] [] i2c_dw_pci_probe+0xa1/0x1d0
[ 3.747987] [] ? rawspin_unlock_irqrestore+0x26/0x50
[ 3.748063] [] pci_device_probe+0x6f/0xb0
[ 3.748128] [] driver_probe_device+0x83/0x3a0
[ 3.748196] [] _driverattach+0x71/0x80
[ 3.748258] [] ? _deviceattach+0x40/0x40
[ 3.748321] [] bus_for_each_dev+0x47/0x80
[ 3.748385] [] driver_attach+0x1e/0x20
[ 3.748445] [] ? _deviceattach+0x40/0x40
[ 3.748508] [] bus_add_driver+0x1cf/0x290
[ 3.748573] [] ? pci_pm_suspend+0x1b0/0x1b0
[ 3.748638] [] ? pci_pm_suspend+0x1b0/0x1b0
[ 3.748702] [] driver_register+0x6a/0x130
[ 3.748764] [] ? mutex_unlock+0xd/0x10
[ 3.748826] [] ? i2c_for_each_dev+0x38/0x50
[ 3.748892] [] ? i2c_gpio_init+0x2e/0x2e
[ 3.748956] [] _pciregister_driver+0x4a/0x50
[ 3.749022] [] dw_i2c_init_driver+0x14/0x16
[ 3.749085] [] do_one_initcall+0xaa/0x160
[ 3.749154] [] kernel_init_freeable+0x126/0x1bd
[ 3.749220] [] ? do_early_param+0x78/0x78
[ 3.749286] [] kernel_init+0x10/0x140
[ 3.749346] [] ret_from_kernel_thread+0x1b/0x28
[ 3.749412] [] ? rest_init+0x80/0x80
[ 3.749514] i2c-designware-pci 0000:00:08.0: ===== REGISTER DUMP (i2c) =====
[ 3.749586] i2c-designware-pci 0000:00:08.0: DW_IC_CON: 0x65
[ 3.749655] i2c-designware-pci 0000:00:08.0: DW_IC_TAR: 0x20
[ 3.749724] i2c-designware-pci 0000:00:08.0: DW_IC_SS_SCL_HCNT: 0x2f8
[ 3.749794] i2c-designware-pci 0000:00:08.0: DW_IC_SS_SCL_LCNT: 0x37b
[ 3.749863] i2c-designware-pci 0000:00:08.0: DW_IC_FS_SCL_HCNT: 0x87
[ 3.749932] i2c-designware-pci 0000:00:08.0: DW_IC_FS_SCL_LCNT: 0x10a
[ 3.750002] i2c-designware-pci 0000:00:08.0: DW_IC_INTR_STAT: 0x0
[ 3.750070] i2c-designware-pci 0000:00:08.0: DW_IC_INTR_MASK: 0x246
[ 3.750139] i2c-designware-pci 0000:00:08.0: DW_IC_RAW_INTR_STAT: 0x10
[ 3.750207] i2c-designware-pci 0000:00:08.0: DW_IC_RX_TL: 0x20
[ 3.750276] i2c-designware-pci 0000:00:08.0: DW_IC_TX_TL: 0x20
[ 3.750345] i2c-designware-pci 0000:00:08.0: DW_IC_ENABLE: 0x1
[ 3.750412] i2c-designware-pci 0000:00:08.0: DW_IC_STATUS: 0x2
[ 3.750480] i2c-designware-pci 0000:00:08.0: DW_IC_TXFLR: 0x3
[ 3.750548] i2c-designware-pci 0000:00:08.0: DW_IC_RXFLR: 0x0
[ 3.750616] i2c-designware-pci 0000:00:08.0: DW_IC_TX_ABRT_SOURCE: 0x0
[ 3.750684] i2c-designware-pci 0000:00:08.0: DW_IC_DATA_CMD: 0x0
[ 3.750751] i2c-designware-pci 0000:00:08.0: ===============================
[ 3.750851] CPU: 0 PID: 1 Comm: swapper/0 Tainted: G W 3.10.98-poky -edison #5
[ 3.750856] Hardware name: Intel Corporation Merrifield/BODEGA BAY, BIOS 466 2014.06.23:19.20.05
[ 3.750863] task: f6880000 ti: f6888000 task.ti: f6888000
[ 3.750871] EIP: 0060:[] EFLAGS: 00000206 CPU: 0
[ 3.750883] EIP is at default_send_IPI_mask_logical+0x8b/0xd0
[ 3.750890] EAX: 00000000 EBX: 03000000 ECX: c1b926a0 EDX: fffff000
[ 3.750897] ESI: 00000206 EDI: 00000002 EBP: f6889a9c ESP: f6889a8c
[ 3.750904] DS: 007b ES: 007b FS: 00d8 GS: 0000 SS: 0068
[ 3.750910] CR0: 8005003b CR2: 00000000 CR3: 01ccd000 CR4: 001007f0
[ 3.750916] DR0: 00000000 DR1: 00000000 DR2: 00000000 DR3: 00000000
[ 3.750920] DR6: ffff0ff0 DR7: 00000400
[ 3.750923] Stack:
[ 3.750946] 00000800 00002710 f6889b70 f5848c24 f6889aa8 c12215c0 00002710 f 6889ab8
[ 3.750967] c122172c c1aa2493 f5848c00 f6889aec c1626788 f60e9064 c1abd8fc 0 0000000
[ 3.750987] c1af17cf 00000000 f5848c98 00000002 f6889af4 f5848c98 00000000 c 1bda628
[ 3.750990] Call Trace:
[ 3.751007] [] default_send_IPI_all+0x60/0x70
[ 3.751021] [] arch_trigger_all_cpu_backtrace+0x4c/0x80
[ 3.751034] [] i2c_dw_xfer+0x448/0x5c0
[ 3.751050] [] _i2ctransfer+0x57/0x70
[ 3.751062] [] i2c_transfer+0x4d/0xc0
[ 3.751075] [] i2c_smbus_xfer+0x21a/0x600
[ 3.751095] [] ? idr_get_empty_slot+0x13f/0x370
[ 3.751108] [] i2c_smbus_read_word_data+0x3b/0x50
[ 3.751121] [] ? sub_preempt_count+0x3d/0x50
[ 3.751135] [] ? rawspin_unlock_irqrestore+0x26/0x50
[ 3.751146] [] ? devres_add+0x38/0x40
[ 3.751161] [] pca953x_read_regs.isra.5+0x2e/0xd0
[ 3.751174] [] ? _mutexinit+0x44/0x50
[ 3.751187] [] pca953x_probe+0x1b2/0x4b0
[ 3.751200] [] ? sysfs_do_create_link_sd+0xac/0x1d0
[ 3.751211] [] ? notifier_call_chain+0x41/0x60
[ 3.751226] [] ? _blockingnotifier_call_chain+0x44/0x60
[ 3.751241] [] i2c_device_probe+0x99/0x110
[ 3.751253] [] ? sysfs_create_link+0x22/0x40
[ 3.751267] [] ? pca953x_irq_handler+0x270/0x270
[ 3.751281] [] driver_probe_device+0x83/0x3a0
[ 3.751293] [] ? sub_preempt_count+0x3d/0x50
[ 3.751306] [] ? driver_probe_device+0x3a0/0x3a0
[ 3.751320] [] ? driver_probe_device+0x3a0/0x3a0
[ 3.751332] [] _deviceattach+0x31/0x40
[ 3.751345] [] bus_for_each_drv+0x47/0x80
[ 3.751358] [] device_attach+0x73/0x90
[ 3.751371] [] ? driver_probe_device+0x3a0/0x3a0
[ 3.751384] [] bus_probe_device+0x6f/0x90
[ 3.751396] [] device_add+0x5a5/0x680
[ 3.751409] [] ? complete_all+0x48/0x50
[ 3.751421] [] ? pm_runtime_init+0xcd/0xe0
[ 3.751434] [] device_register+0x17/0x20
[ 3.751445] [] i2c_new_device+0x128/0x1c0
[ 3.751460] [] ? class_compat_create_link+0x48/0x80
[ 3.751473] [] i2c_register_adapter+0x1d7/0x310
[ 3.751485] [] i2c_add_numbered_adapter+0x59/0x90
[ 3.751498] [] i2c_dw_setup+0x282/0x330
[ 3.751512] [] i2c_dw_pci_probe+0xa1/0x1d0
[ 3.751526] [] ? rawspin_unlock_irqrestore+0x26/0x50
[ 3.751542] [] pci_device_probe+0x6f/0xb0
[ 3.751556] [] driver_probe_device+0x83/0x3a0
[ 3.751571] [] _driverattach+0x71/0x80
[ 3.751584] [] ? _deviceattach+0x40/0x40
[ 3.751596] [] bus_for_each_dev+0x47/0x80
[ 3.751609] [] driver_attach+0x1e/0x20
[ 3.751621] [] ? _deviceattach+0x40/0x40
[ 3.751634] [] bus_add_driver+0x1cf/0x290
[ 3.751648] [] ? pci_pm_suspend+0x1b0/0x1b0
[ 3.751662] [] ? pci_pm_suspend+0x1b0/0x1b0
[ 3.751675] [] driver_register+0x6a/0x130
[ 3.751687] [] ? mutex_unlock+0xd/0x10
[ 3.751701] [] ? i2c_for_each_dev+0x38/0x50
[ 3.751715] [] ? i2c_gpio_init+0x2e/0x2e
[ 3.751729] [] _pciregister_driver+0x4a/0x50
[ 3.751742] [] dw_i2c_init_driver+0x14/0x16
[ 3.751753] [] do_one_initcall+0xaa/0x160
[ 3.751769] [] kernel_init_freeable+0x126/0x1bd
[ 3.751782] [] ? do_early_param+0x78/0x78
[ 3.751796] [] kernel_init+0x10/0x140
[ 3.751808] [] ret_from_kernel_thread+0x1b/0x28
[ 3.751820] [] ? rest_init+0x80/0x80
[ 3.751937] Code: b3 ff ff 89 f8 09 d0 80 ce 04 83 ff 02 0f 44 c2 8b 15 94 2b b9 c1 89 82 00 b3 ff ff f7 c6 00 02 00 00 74 14 e8 57 03 0b 00 56 9d <83> c4 04 5b 5e 5f 5d c3 90 8d 74 26 00 56 9d e8 41 ff 0a 00 83
[ 3.751958] CPU: 1 PID: 0 Comm: swapper/1 Tainted: G W 3.10.98-poky -edison #5
[ 3.751963] Hardware name: Intel Corporation Merrifield/BODEGA BAY, BIOS 466 2014.06.23:19.20.05
[ 3.751971] task: f6883de0 ti: f6a1e000 task.ti: f6a1e000
[ 3.751979] EIP: 0060:[] EFLAGS: 00200286 CPU: 1
[ 3.751993] EIP is at default_idle+0x22/0xf0
[ 3.752000] EAX: 00000000 EBX: 02100800 ECX: 00000000 EDX: 00000000
[ 3.752006] ESI: 00000000 EDI: 00000001 EBP: f6a1ff70 ESP: f6a1ff64
[ 3.752013] DS: 007b ES: 007b FS: 00d8 GS: 0000 SS: 0068
[ 3.752019] CR0: 8005003b CR2: 00000000 CR3: 01ccd000 CR4: 001007f0
[ 3.752025] DR0: 00000000 DR1: 00000000 DR2: 00000000 DR3: 00000000
[ 3.752029] DR6: ffff0ff0 DR7: 00000400
[ 3.752032] Stack:
[ 3.752056] 02100800 00000000 f6a1e000 f6a1ff78 c12081a6 f6a1ff94 c1284577 f fffffff
[ 3.752075] 00000000 02100800 00000000 00000000 f6a1ffb4 c18ad602 00000000 0 0000000
[ 3.752093] 00000000 00000000 00000001 00200002 00000000 00000000 00000000 0 0000000
[ 3.752096] Call Trace:
[ 3.752114] [] arch_cpu_idle+0x26/0x30
[ 3.752130] [] cpu_startup_entry+0x107/0x210
[ 3.752145] [] start_secondary+0x234/0x236
[ 3.752264] Code: c6 0f 86 85 fe ff ff eb d0 55 89 e5 57 56 53 3e 8d 74 26 00 a1 5c e5 c0 c1 64 8b 3d 10 c0 cb c1 85 c0 75 1c e8 d0 9e 0c 00 fb f4 5c e5 c0 c1 64 8b 3d 10 c0 cb c1 85 c0 75 54 5b 5e 5f 5d c3
[ 3.752948] i2c-1: try to abort xfer, scl_gpio 19, sda_gpio 20
[ 4.839187] i2c-1: scl_gpio val 1, sda_gpio val 0
[ 4.843817] i2c-1: toggle begin
[ 4.843987] i2c-1: toggle SCL loop 0
[ 4.850562] i2c-1: toggle SCL loop 1
[ 4.854106] i2c-1: toggle SCL loop 2
[ 4.854335] i2c-1: toggle SCL loop 3
[ 4.854507] i2c-1: toggle SCL loop 4
[ 4.854660] i2c-1: toggle SCL loop 5
[ 4.854806] i2c-1: toggle SCL loop 6
[ 4.854952] i2c-1: toggle SCL loop 7
[ 4.855110] i2c-1: toggle SCL loop 8
[ 4.855155] i2c-1: toggle end
[ 4.855575] pca953x 1-0020: failed reading register
[ 7.853954] Device: i2c-designware-pci
[ 7.853954] controller timed out
[ 7.854037] Modules linked in:
[ 7.854090] CPU: 0 PID: 1 Comm: swapper/0 Tainted: G W 3.10.98-poky -edison #5
[ 7.854163] Hardware name: Intel Corporation Merrifield/BODEGA BAY, BIOS 466 2014.06.23:19.20.05
[ 7.854241] f6889ab0 f6889ab0 f6889a78 c18b64f8 f6889aa0 c123e9ee c1b13ec0 f 6889acc
[ 7.854365] 000004d7 c1626520 c1626520 f5848c00 f6889b70 f5848c24 f6889ab8 c 123ea43
[ 7.854486] 00000009 f6889ab0 c1b13ec0 f6889acc f6889aec c1626520 c1b13ee4 0 00004d7
[ 7.854608] Call Trace:
[ 7.854656] [] dump_stack+0x16/0x18
[ 7.854719] [] warn_slowpath_common+0x5e/0x80
[ 7.854786] [] ? i2c_dw_xfer+0x1e0/0x5c0
[ 7.854847] [] ? i2c_dw_xfer+0x1e0/0x5c0
[ 7.854910] [] warn_slowpath_fmt+0x33/0x40
[ 7.854974] [] i2c_dw_xfer+0x1e0/0x5c0
[ 7.855040] [] _i2ctransfer+0x57/0x70
[ 7.855101] [] i2c_transfer+0x4d/0xc0
[ 7.855162] [] i2c_smbus_xfer+0x21a/0x600
[ 7.855226] [] ? format_decode+0x323/0x390
[ 7.855296] [] ? sprintf+0x1c/0x20
[ 7.855356] [] ? print_time.part.2+0x71/0xb0
[ 7.855423] [] ? idr_get_empty_slot+0x13f/0x370
[ 7.855491] [] i2c_smbus_read_word_data+0x3b/0x50
[ 7.855559] [] ? sub_preempt_count+0x3d/0x50
[ 7.855625] [] ? rawspin_unlock_irqrestore+0x26/0x50
[ 7.855694] [] ? devres_add+0x38/0x40
[ 7.855757] [] pca953x_read_regs.isra.5+0x2e/0xd0
[ 7.855825] [] ? _mutexinit+0x44/0x50
[ 7.855888] [] pca953x_probe+0x1b2/0x4b0
[ 7.855950] [] ? sysfs_do_create_link_sd+0xac/0x1d0
[ 7.856018] [] ? notifier_call_chain+0x41/0x60
[ 7.856087] [] ? _blockingnotifier_call_chain+0x44/0x60
[ 7.856163] [] i2c_device_probe+0x99/0x110
[ 7.856226] [] ? sysfs_create_link+0x22/0x40
[ 7.856292] [] ? pca953x_irq_handler+0x270/0x270
[ 7.856361] [] driver_probe_device+0x83/0x3a0
[ 7.856426] [] ? sub_preempt_count+0x3d/0x50
[ 7.856491] [] ? driver_probe_device+0x3a0/0x3a0
[ 7.856559] [] ? driver_probe_device+0x3a0/0x3a0
[ 7.856626] [] _deviceattach+0x31/0x40
[ 7.856688] [] bus_for_each_drv+0x47/0x80
[ 7.856752] [] device_attach+0x73/0x90
[ 7.856813] [] ? driver_probe_device+0x3a0/0x3a0
[ 7.856881] [] bus_probe_device+0x6f/0x90
[ 7.856944] [] device_add+0x5a5/0x680
[ 7.857005] [] ? complete_all+0x48/0x50
[ 7.857066] [] ? pm_runtime_init+0xcd/0xe0
[ 7.857131] [] device_register+0x17/0x20
[ 7.857192] [] i2c_new_device+0x128/0x1c0
[ 7.857257] [] ? class_compat_create_link+0x48/0x80
[ 7.857326] [] i2c_register_adapter+0x1d7/0x310
[ 7.857394] [] i2c_add_numbered_adapter+0x59/0x90
[ 7.857462] [] i2c_dw_setup+0x282/0x330
[ 7.857527] [] i2c_dw_pci_probe+0xa1/0x1d0
[ 7.857592] [] ? rawspin_unlock_irqrestore+0x26/0x50
[ 7.857667] [] pci_device_probe+0x6f/0xb0
[ 7.857731] [] driver_probe_device+0x83/0x3a0
[ 7.857800] [] _driverattach+0x71/0x80
[ 7.857862] [] ? _deviceattach+0x40/0x40
[ 7.857925] [] bus_for_each_dev+0x47/0x80
[ 7.857989] [] driver_attach+0x1e/0x20
[ 7.858050] [] ? _deviceattach+0x40/0x40
[ 7.858113] [] bus_add_driver+0x1cf/0x290
[ 7.858178] [] ? pci_pm_suspend+0x1b0/0x1b0
[ 7.858243] [] ? pci_pm_suspend+0x1b0/0x1b0
[ 7.858307] [] driver_register+0x6a/0x130
[ 7.858369] [] ? mutex_unlock+0xd/0x10
[ 7.858431] [] ? i2c_for_each_dev+0x38/0x50
[ 7.858496] [] ? i2c_gpio_init+0x2e/0x2e
[ 7.858560] [] _pciregister_driver+0x4a/0x50
[ 7.858626] [] dw_i2c_init_driver+0x14/0x16
[ 7.858689] [] do_one_initcall+0xaa/0x160
[ 7.858756] [] kernel_init_freeable+0x126/0x1bd
[ 7.858823] [] ? do_early_param+0x78/0x78
[ 7.858889] [] kernel_init+0x10/0x140
[ 7.858949] [] ret_from_kernel_thread+0x1b/0x28
[ 7.859015] [] ? rest_init+0x80/0x80
[ 7.859089] i2c-designware-pci 0000:00:08.0: ===== REGISTER DUMP (i2c) =====
[ 7.859160] i2c-designware-pci 0000:00:08.0: DW_IC_CON: 0x65
[ 7.859228] i2c-designware-pci 0000:00:08.0: DW_IC_TAR: 0x21
[ 7.859297] i2c-designware-pci 0000:00:08.0: DW_IC_SS_SCL_HCNT: 0x2f8
[ 7.859367] i2c-designware-pci 0000:00:08.0: DW_IC_SS_SCL_LCNT: 0x37b
[ 7.859436] i2c-designware-pci 0000:00:08.0: DW_IC_FS_SCL_HCNT: 0x87
[ 7.859505] i2c-designware-pci 0000:00:08.0: DW_IC_FS_SCL_LCNT: 0x10a
[ 7.859574] i2c-designware-pci 0000:00:08.0: DW_IC_INTR_STAT: 0x0
[ 7.859643] i2c-designware-pci 0000:00:08.0: DW_IC_INTR_MASK: 0x246
[ 7.859712] i2c-designware-pci 0000:00:08.0: DW_IC_RAW_INTR_STAT: 0x10
[ 7.859781] i2c-designware-pci 0000:00:08.0: DW_IC_RX_TL: 0x20
[ 7.859849] i2c-designware-pci 0000:00:08.0: DW_IC_TX_TL: 0x20
[ 7.859918] i2c-designware-pci 0000:00:08.0: DW_IC_ENABLE: 0x1
[ 7.859986] i2c-designware-pci 0000:00:08.0: DW_IC_STATUS: 0x2
[ 7.860053] i2c-designware-pci 0000:00:08.0: DW_IC_TXFLR: 0x3
[ 7.860121] i2c-designware-pci 0000:00:08.0: DW_IC_RXFLR: 0x0
[ 7.860189] i2c-designware-pci 0000:00:08.0: DW_IC_TX_ABRT_SOURCE: 0x0
[ 7.860257] i2c-designware-pci 0000:00:08.0: DW_IC_DATA_CMD: 0x0
[ 7.860324] i2c-designware-pci 0000:00:08.0: ===============================

**Comment by scottleibrand** [comment]
I don't see any errors there. Have you already joined https://gitter.im/nightscout/intend-to-bolus for troubleshooting help?
