### ISSUE TITLE
C10/C14 Capacitors

### ISSUE THREAD

**Issue by infoneo** [EnhancedRadioDevices/915MHzEdisonExplorer#21]
Do the C10/C14 capacitors shouldn't be about 31pF   =2*(18pF-2,5pF)
According to CC1110 datasheet - "9.3 Crystal"

**Comment by mogar** [comment]
To determine correct capacitor values, you need to look at the exact oscillator you're going to use (which in our case is a 7V-24.000MAHJ-T). The crystal on the Explorer Block requires`18pF loading capacitance. We get pretty close to that with the 18pF capacitors and the parasitic capacitance on the board (we may be a bit low, but the oscillator works well).

I also think your math might be off. The equation in the datasheet is Cl = 1/(1/C1 + 1/C2) + Cp.
For us that's Cl = 1/(1/18pf + 1/18pf) + 2.5pf = 11.5pf.

**Comment by mogar** [comment]
After thinking about a bit more, I see what you're asking. Yes, 31pF capacitors would get us close to the nominal values for our crystal. You're right about that. The oscillator functions as is, so we're going to leave it.
