### ISSUE TITLE
Reset button for Edison

### ISSUE THREAD

**Issue by mogar** [EnhancedRadioDevices/915MHzEdisonExplorer#5]
It would be good to have a reset button for the Edison, so that it doesn't always get turned off with a hard power cycle.

**Comment by oskarpearson** [comment]
Technical info:
http://download.intel.com/support/edison/sb/edisonbreakout_hg_331190006.pdf lists the button as being J18 - pin 3.

http://download.intel.com/support/edison/sb/edisonmodule_hg_331189004.pdf page 14 lists pin 17 as "power/sleep button input (active low)"

**Comment by mogar** [comment]
Including on next revision.
